export const projects = [
    {
        id: 1110286,
        title: 'Web App',
        subtitle: 'PREMIUM',
        position: 'Full-stack',
        year: '2024',
        description: 'DREXUS is a strategic digital marketing agency based in Kampala, Uganda that has dedicated their time to understanding what works — so you don\'t have to.',
        skills: ['Nest', 'Type ORM', 'Postgres','NextJS', 'Redux', 'Typescript'],
        img: 'drexus-cover-web-app.jpg',
        source_code: 'https://github.com/chiztechnology/drexus-frontend',
        live_version: 'https://drexus.chiztechnology.com/',
      },
    {
      id: 1110226,
      title: 'Blog App',
      subtitle: 'PREMIUM',
      position: 'Full-stack',
      year: '2024',
      description: 'Introducing my latest project, a dynamic and user-friendly blog application designed to provide a seamless reading and writing experience. This app allows users to effortlessly create, share, and explore a wide range of articles. Built with modern web technologies, it features an intuitive interface, customizable URLs for each blog post, and robust metadata management for optimal SEO performance. Readers can easily share their favorite articles on social media platforms like LinkedIn, Twitter, Facebook, and WhatsApp. With a responsive design, the blog app ensures a great experience on both desktop and mobile devices. Check out the screenshot below to see it in action!',
      skills: ['Nest', 'Hono server','Type ORM', 'Postgres','NextJS', 'Redux', 'Typescript'],
      img: 'blessing-reformed-blog-cover.png',
      source_code: 'https://github.com/chiztechnology/blessing-reformed-frontend',
      live_version: 'https://www.blessingreformed.org/',
    },
    {
      id: 1110166,
      title: 'Landing Page',
      subtitle: 'OPEN S.',
      position: 'UI/UX Design',
      year: '2022',
      description: 'this is a free open source project to help developers develop their online presence and get started with figma tool. Feel free to check it out and contribute',
      skills: ['Figma', 'Photoshop',],
      img: 'landing-page_figma_presentation.png',
      source_code: 'https://www.figma.com/design/36G8wFnB9QaGVjJ9I0K7Qt/Portfolio-Figma-design?node-id=0-1&t=Ml9KJd5jukgLDjbd-0',
      live_version: 'https://www.figma.com/design/36G8wFnB9QaGVjJ9I0K7Qt/Portfolio-Figma-design?node-id=0-1&t=Ml9KJd5jukgLDjbd-0',
    },
      {
      id: 1200166,
      title: 'GrowChief',
      subtitle: 'OPEN S.',
      position: 'Frontend',
      year: '2024',
      description: 'GrowChief is an open source Landing page built in NextJS from a figma open source template available on the web. star the github repository and feel free to contribute',
      skills: ['Figma', 'Nextjs', 'Typescript','Javascript'],
      img: 'Growchief landing page.jpg',
      source_code: 'https://github.com/chiztechnology/growchief',
      live_version: 'https://growchief.onrender.com/',
    },{
      id: 120014,
      title: 'UPDEV C.',
      subtitle: 'OPEN S.',
      position: 'Contributor',
      year: '2023',
      description: 'UPDEV Community is a Room for developers to connect, learn, share skills and knowledge and grow as a community...',
      skills: ['React', 'Nextjs', 'Typescript', 'Nest JS', 'Nodejs', 'MongoDB', 'Javascript'],
      img: 'Updev community.jpg',
      source_code: 'https://github.com/UPTODATE-DEV/updevcommunity-frontend',
      live_version: 'https://updevcommunity.com/en',
    },
    {
      id: 12214,
      title: 'PCV Academy',
      subtitle: 'OPEN S.',
      position: 'Full stack',
      year: '2023',
      description: 'PCV Academy, an online platform for registering students, posting public announcements and facilitating communication between school and parents...',
      skills: ['React', 'Nextjs', 'Typescript', 'Tailwind CSS', 'Nodejs', 'Git', 'Javascript'],
      img: 'PCV Academy.jpg',
      source_code: 'https://github.com/chiztechnology/anzasport.git',
      live_version: 'https://pcv-academy.onrender.com',
    },
    {
      id: 14,
      title: 'Car Hub',
      subtitle: 'OPEN S.',
      position: 'Front-end',
      year: '2023',
      description: 'Introducing CarHub, a sleek and intuitive car renting application designed for a seamless user experience. Built with Next.js and TypeScript, CarHub combines cutting-edge technology with robust functionality...',
      skills: ['React', 'Nextjs', 'Typescript', 'Tailwind CSS', 'Git', 'Javascript'],
      img: 'car renting app preview.jpg',
      source_code: 'https://github.com/chiztechnology/car-renting',
      live_version: 'https://car-renting-4slnt1vyl-chiztechnology.vercel.app/',
    },
    {
      id: 142134,
      title: 'Car renting app',
      subtitle: 'CAPSTONE',
      position: 'Full-Stack',
      year: '2023',
      description: 'CAR BOOKING is a platform built in two different apps that allow users to reserve cars for renting. the user can browse the list of cars and show details for each car, the user can submit a reservation form and can cancel reservation...',
      skills: ['React', 'Ruby', 'Rails', 'Javascript', 'Git', 'Pair-programming'],
      img: 'car-renting-app-overview.png',
      source_code: 'https://github.com/sajibarafatsiddiqui/final-capstone-project',
      live_version: '#',
    },
    {
      id: 1,
      title: 'Africa Summit',
      subtitle: 'Af. SUM',
      position: 'Front-End Dev',
      year: '2022',
      description: 'Africa-Summit is a project that presents an online conference attendance page with some features that allow visitors to get informed about...',
      skills: ['html', 'css', 'javascript'],
      img: 'cc-global-summit-work.png',
      source_code: 'https://github.com/chiztechnology/Africa-Summit',
      live_version: 'https://chiztechnology.github.io/Africa-Summit/index.html',
    },
    {
      id: 2,
      title: 'TODO-List App',
      subtitle: 'ES6',
      position: 'Back End Dev',
      year: '2022',
      description: 'we built a simple todolist that allows users to add/remove tasks or mark them as finished from a list. we achieved it that by using JavaScript ...',
      skills: ['html', 'css', 'javascript'],
      img: 'todo-sc-work.png',
      source_code: 'https://github.com/chiztechnology/Todo-List',
      live_version: 'https://chiztechnology.github.io/Todo-List/dist/',
    },
  ];